apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
    spring.datasource.url: jdbc:mysql://mysql:3306/ems
    spring.datasource.driverClassName: com.mysql.jdbc.Driver
    spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
 
